"""
logging_config.yaml
This contains the configurations used for logging
"""
version: 1
disable_existing_loggers:false
formatters:
  dev:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s - %(lineno)d'

  user:
    format:'%(asctime)s - %(levelname)s - %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler # messages to the terminal
    level: DEBUG
    formatter: dev
  file:
    class: logging.handerlers.TimeRotatingFileHandler
    level: INFO
    formatter: user
    filename: logs.log
    when: midnight
    interval: 1
    backupCount: 7
    maxBytes: 300
root:
  level: INFO
  handlers:
    - file




